load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "deploy",
    srcs = [
        "deploy.go",
        "persistentworker.go",
        "sign.go",
        "sink.go",
    ],
    importpath = "github.com/bazel-contrib/rules_img/img_tool/cmd/deploy",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/api",
        "//pkg/auth/credential",
        "//pkg/auth/protohelper",
        "//pkg/auth/registry",
        "//pkg/cas",
        "//pkg/deployvfs",
        "//pkg/gateway",
        "//pkg/load",
        "//pkg/ocilayout",
        "//pkg/persistentworker",
        "//pkg/progress",
        "//pkg/proto/blobcache",
        "//pkg/push",
        "//pkg/registryfallback",
        "//pkg/registryopts",
        "//pkg/signer",
        "@com_github_google_go_containerregistry//pkg/name",
        "@com_github_google_go_containerregistry//pkg/v1:pkg",
        "@com_github_google_go_containerregistry//pkg/v1/remote",
        "@com_github_google_go_containerregistry//pkg/v1/types",
        "@org_golang_x_sync//errgroup",
        "@rules_go//go/runfiles",
    ],
)

go_test(
    name = "deploy_test",
    srcs = [
        "progress_test.go",
        "sign_sink_test.go",
        "sink_test.go",
        "sink_vfs_test.go",
    ],
    embed = [":deploy"],
    deps = [
        "//pkg/api",
        "//pkg/deployvfs",
        "//pkg/ocilayout",
        "//pkg/progress",
        "@com_github_google_go_containerregistry//pkg/v1:pkg",
        "@com_github_google_go_containerregistry//pkg/v1/empty",
        "@com_github_google_go_containerregistry//pkg/v1/mutate",
        "@com_github_google_go_containerregistry//pkg/v1/static",
        "@com_github_google_go_containerregistry//pkg/v1/types",
    ],
)
