load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "dockersave",
    srcs = [
        "dockersave.go",
        "flags.go",
        "sink.go",
    ],
    importpath = "github.com/bazel-contrib/rules_img/img_tool/cmd/dockersave",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/ocitar",
        "@com_github_google_go_containerregistry//pkg/v1:pkg",
        "@com_github_google_go_containerregistry//pkg/v1/types",
    ],
)

go_test(
    name = "dockersave_test",
    srcs = ["dockersave_test.go"],
    embed = [":dockersave"],
    deps = [
        "@com_github_google_go_containerregistry//pkg/v1:pkg",
        "@com_github_google_go_containerregistry//pkg/v1/types",
    ],
)
