load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "push",
    srcs = ["push.go"],
    importpath = "github.com/bazel-contrib/rules_img/img_tool/pkg/push",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/api",
        "//pkg/progress",
        "//pkg/proto/blobcache",
        "//pkg/proto/remote-apis/build/bazel/remote/execution/v2",
        "//pkg/registryfallback",
        "//pkg/registryopts",
        "@com_github_google_go_containerregistry//pkg/name",
        "@com_github_google_go_containerregistry//pkg/v1:pkg",
        "@com_github_google_go_containerregistry//pkg/v1/remote",
        "@org_golang_x_sync//errgroup",
    ],
)

go_test(
    name = "push_test",
    size = "small",
    srcs = ["push_test.go"],
    embed = [":push"],
    deps = [
        "//pkg/api",
        "//pkg/progress",
        "//pkg/registryopts",
        "@com_github_google_go_containerregistry//pkg/authn",
        "@com_github_google_go_containerregistry//pkg/logs",
        "@com_github_google_go_containerregistry//pkg/registry",
        "@com_github_google_go_containerregistry//pkg/v1:pkg",
        "@com_github_google_go_containerregistry//pkg/v1/mutate",
        "@com_github_google_go_containerregistry//pkg/v1/random",
        "@com_github_google_go_containerregistry//pkg/v1/remote",
        "@com_github_google_go_containerregistry//pkg/v1/types",
    ],
)
