load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "push",
    srcs = [
        "blob.go",
        "manifest.go",
        "push.go",
    ],
    importpath = "github.com/bazel-contrib/rules_img/img_tool/cmd/push",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/api",
        "//pkg/compactstream",
        "//pkg/deployvfs",
        "//pkg/gateway",
        "//pkg/push",
        "//pkg/registryfallback",
        "//pkg/registryopts",
        "@com_github_google_go_containerregistry//pkg/name",
        "@com_github_google_go_containerregistry//pkg/v1:pkg",
        "@com_github_google_go_containerregistry//pkg/v1/remote",
    ],
)

go_test(
    name = "push_test",
    srcs = ["blob_test.go"],
    embed = [":push"],
    deps = [
        "//pkg/api",
        "@com_github_google_go_containerregistry//pkg/name",
        "@com_github_google_go_containerregistry//pkg/registry",
        "@com_github_google_go_containerregistry//pkg/v1/remote",
    ],
)
